package shortestpath;

public interface ShortestPathConfig {
    default boolean avoidWilderness() { return true; }
    default boolean useAgilityShortcuts() { return true; }
    default boolean useGrappleShortcuts() { return false; }
    default boolean useBoats() { return true; }
    default boolean useCanoes() { return false; }
    default boolean useCharterShips() { return false; }
    default boolean useShips() { return true; }
    default boolean useFairyRings() { return true; }
    default boolean useGnomeGliders() { return true; }
    default boolean useHotAirBalloons() { return false; }
    default boolean useMagicCarpets() { return true; }
    default boolean useMagicMushtrees() { return true; }
    default boolean useMinecarts() { return true; }
    default boolean useQuetzals() { return true; }
    default boolean useSpiritTrees() { return true; }
    default TeleportationItem useTeleportationItems() { return TeleportationItem.INVENTORY_NON_CONSUMABLE; }
    default boolean useTeleportationLevers() { return true; }
    default boolean useTeleportationPortals() { return true; }
    default boolean useTeleportationSpells() { return true; }
    default boolean useTeleportationMinigames() { return true; }
    default boolean useWildernessObelisks() { return true; }
    default boolean useSeasonalTransports() { return false; }
    default boolean includeBankPath() { return false; }
    default int currencyThreshold() { return 100000; }
    default int calculationCutoff() { return 5; }
    default boolean usePoh() { return false; }
    default boolean usePohFairyRing() { return false; }
    default boolean usePohSpiritTree() { return false; }
    default boolean useTeleportationPortalsPoh() { return false; }
    default JewelleryBoxTier pohJewelleryBoxTier() { return JewelleryBoxTier.ORNATE; }
    default boolean usePohMountedItems() { return true; }
    default boolean usePohObelisk() { return false; }
    default int costAgilityShortcuts() { return 0; }
    default int costGrappleShortcuts() { return 0; }
    default int costBoats() { return 0; }
    default int costCanoes() { return 0; }
    default int costCharterShips() { return 0; }
    default int costShips() { return 0; }
    default int costFairyRings() { return 0; }
    default int costGnomeGliders() { return 0; }
    default int costHotAirBalloons() { return 0; }
    default int costMagicCarpets() { return 0; }
    default int costMagicMushtrees() { return 0; }
    default int costMinecarts() { return 0; }
    default int costQuetzals() { return 0; }
    default int costSeasonalTransports() { return 0; }
    default int costSpiritTrees() { return 0; }
    default int costNonConsumableTeleportationItems() { return 0; }
    default int costConsumableTeleportationItems() { return 0; }
    default int costTeleportationBoxes() { return 0; }
    default int costTeleportationLevers() { return 0; }
    default int costTeleportationMinigames() { return 0; }
    default int costTeleportationPortals() { return 0; }
    default int costTeleportationSpells() { return 0; }
    default int costWildernessObelisks() { return 0; }
}
