package com.kraken.llms;

import jdk.javadoc.doclet.Doclet;
import jdk.javadoc.doclet.DocletEnvironment;
import jdk.javadoc.doclet.Reporter;

import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.ElementFilter;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Collectors;

/**
 * Javadoc doclet that writes a compact, Java-stub style dump of every public and protected type and member
 * in the API, each preceded by the first sentence of its Javadoc. Members generated by Lombok annotations are
 * included so the dump matches what plugin code can actually call.
 */
public class ApiSignatureDoclet implements Doclet {

    private Reporter reporter;
    private Path outputFile;

    @Override
    public void init(Locale locale, Reporter reporter) {
        this.reporter = reporter;
    }

    @Override
    public String getName() {
        return "ApiSignatureDoclet";
    }

    @Override
    public Set<? extends Option> getSupportedOptions() {
        return Set.of(new Option() {
            @Override
            public int getArgumentCount() {
                return 1;
            }

            @Override
            public String getDescription() {
                return "File the signature dump is written to";
            }

            @Override
            public Kind getKind() {
                return Kind.STANDARD;
            }

            @Override
            public List<String> getNames() {
                return List.of("--output");
            }

            @Override
            public String getParameters() {
                return "<file>";
            }

            @Override
            public boolean process(String option, List<String> arguments) {
                outputFile = Path.of(arguments.get(0));
                return true;
            }
        });
    }

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latest();
    }

    @Override
    public boolean run(DocletEnvironment environment) {
        if (outputFile == null) {
            reporter.print(Diagnostic.Kind.ERROR, "--output is required");
            return false;
        }

        SignatureRenderer renderer = new SignatureRenderer(environment);

        // Only top-level types are collected here; nested types are rendered inside their enclosing type.
        Map<String, List<TypeElement>> typesByPackage = new TreeMap<>();
        for (TypeElement type : ElementFilter.typesIn(environment.getIncludedElements())) {
            if (type.getEnclosingElement().getKind() != ElementKind.PACKAGE) {
                continue;
            }
            String packageName = ((PackageElement) type.getEnclosingElement()).getQualifiedName().toString();
            typesByPackage.computeIfAbsent(packageName, key -> new ArrayList<>()).add(type);
        }

        StringBuilder output = new StringBuilder();
        for (Map.Entry<String, List<TypeElement>> entry : typesByPackage.entrySet()) {
            PackageElement packageElement = environment.getElementUtils().getPackageElement(entry.getKey());
            output.append("package ").append(entry.getKey()).append(";\n");
            String packageSummary = renderer.summary(packageElement);
            if (!packageSummary.isEmpty()) {
                output.append("// ").append(packageSummary).append('\n');
            }
            output.append('\n');

            List<TypeElement> types = entry.getValue().stream()
                    .sorted(Comparator.comparing((Element element) -> element.getSimpleName().toString()))
                    .collect(Collectors.toList());
            for (TypeElement type : types) {
                renderer.renderType(type, "", output);
                output.append('\n');
            }
        }

        try {
            Files.createDirectories(outputFile.toAbsolutePath().getParent());
            Files.writeString(outputFile, output.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            reporter.print(Diagnostic.Kind.ERROR, "Failed to write " + outputFile + ": " + e.getMessage());
            return false;
        }
        return true;
    }
}
