name: Artifact Cleanup

on:
  push:
    branches:
      - main
      - master
      - develop
  schedule:
    - cron: '0 4 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      actions: write

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '3 month'
          skip-recent: 20
