name: Package Cleanup

on:
  push:
    branches:
      - main
      - master
      - develop
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  packages: write

jobs:
  remove-old-packages:
    runs-on: ubuntu-latest
    environment: Prod
    timeout-minutes: 10

    steps:
      - name: Delete old versions (com.github.cbartram.kraken-api)
        uses: actions/delete-package-versions@v5
        with:
          package-name: com.github.cbartram.kraken-api
          package-type: maven
          min-versions-to-keep: 5
          delete-only-untagged-versions: false
          token: ${{ secrets.CLEANUP_PAT }}
        continue-on-error: true

      - name: Delete old versions (com.github.kraken.kraken-api)
        uses: actions/delete-package-versions@v5
        with:
          package-name: com.github.kraken.kraken-api
          package-type: maven
          min-versions-to-keep: 5
          delete-only-untagged-versions: false
          token: ${{ secrets.CLEANUP_PAT }}
        continue-on-error: true